schemaVersion: 2.2.0
metadata:
  name: 'python-kedro-environment'
attributes:
  space:
    instanceType: large
    editor:
      type: PyCharm
      version: '2022.1'
      updateChannel: EAP
      vmoptions:
      - '-Xms2048m'
      - '-Xmx4096m'
components:
- name: dev-container
  container:
    image: ubuntu:22.04
    env:
      - name: DEBIAN_FRONTEND
        value: 'noninteractive'
    command: 
      - /bin/bash
      - '-c'
      - |
        apt-get update && apt-get install -y wget bzip2
        wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
        bash Miniconda3-latest-Linux-x86_64.sh -b -p $HOME/miniconda
        eval "$($HOME/miniconda/bin/conda shell.bash hook)"
        conda create --name kedro-environment python=3.10 -y
        conda activate kedro-environment
        pip install -r src/requirements.txt

